In [1]:
import pandas as pd
import time
import numpy as np
from collections import Counter
data=pd.read_csv('30cst5items.csv', encoding='utf-16', sep='\t')
data=data.fillna(0)
data

,Customer_Id,133896,131802,131709,131701,131350,131302,123722,123695,123389,...,24693,24584,24550,24486,24361,24106,23973,23850,23782,22122
0,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,90,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,150,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,204,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,213,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,140160,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
293,141998,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
294,144102,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
295,149688,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
296,180423,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [2]:
def slice_cols(j):
    l=[]
    for i in range(1,data.shape[1]):
        if i!=j:
            l.append(i)
    return l

def slice_raws(i):
    lr=[]
    for n in range(data.shape[0]):
        if n!=i:
            lr.append(n)
    return lr

In [3]:
cur_time = time.time()
customer_id=47059
i=data[data['Customer_Id']==customer_id].index.values.astype(int)[0]
metrics={}
for j in range(1, data.shape[1]):
    if data.iloc[i,j]==0:
        sum_m=[]
        sum_c=[]
        a=data.iloc[i, slice_cols(j)]
        for k in slice_raws(i):
            b=data.iloc[k, slice_cols(j)]
            d=np.linalg.norm(a-b)
            m=data.iloc[k,j]/d
            c=1/d
            sum_m.append(m)
            sum_c.append(c)
        metric=round(1/sum(sum_c)*sum(sum_m),2)
        metrics[data.iloc[i,0],list(data.columns)[j]]=metric
metrics=dict(sorted(metrics.items(), key=lambda item: item[1]))
k = Counter(metrics)
high = k.most_common(3)
for i in high:
    #if i[1]>=0.5:
    print(i[0]," :",i[1]," ")
print('Seconds for processing ', round(time.time() - cur_time, 2))

(47059, '25344')  : 0.1
(47059, '26645')  : 0.09
(47059, '26571')  : 0.08
Seconds for processing  48.02