In [1]:
import pandas as pd
ss = pd.read_csv('ss_30Sep2020.csv')
ss.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 494 entries, 0 to 493
Data columns (total 26 columns):
admin_url                          494 non-null object
"buy_decision_time"                494 non-null object
"changes_requested"                494 non-null object
"communication_method_readable"    494 non-null object
"communication_method"             493 non-null float64
"created_at"                       494 non-null object
"created_by"                       494 non-null int64
"customer"                         494 non-null int64
"customer_admin_url"               494 non-null object
"discover_by"                      0 non-null float64
"does_price_matter"                221 non-null object
"email"                            494 non-null object
"having_rep"                       147 non-null object
"id"                               494 non-null int64
"likes_least"                      51 non-null object
"likes_most"                       0 non-null float64
"mainly_puchase_from"              494 non-null object
"monthly_spend"                    494 non-null int64
"name"                             481 non-null object
"parts_type"                       494 non-null object
"purchase_frequency_readable"      494 non-null object
"purchase_frequency"               494 non-null int64
"recommendation"                   494 non-null object
"satisfaction"                     494 non-null int64
"sending_po_easier"                166 non-null object
"tshirt_size"                      432 non-null object
dtypes: float64(3), int64(6), object(17)
memory usage: 100.5+ KB

In [2]:
new_columns=[]
for c in ss.columns:
    clean_c=c.replace('"', "")
    new_columns.append(clean_c)   
ss.columns=new_columns
ss.columns

Index(['admin_url', 'buy_decision_time', 'changes_requested',
       'communication_method_readable', 'communication_method', 'created_at',
       'created_by', 'customer', 'customer_admin_url', 'discover_by',
       'does_price_matter', 'email', 'having_rep', 'id', 'likes_least',
       'likes_most', 'mainly_puchase_from', 'monthly_spend', 'name',
       'parts_type', 'purchase_frequency_readable', 'purchase_frequency',
       'recommendation', 'satisfaction', 'sending_po_easier', 'tshirt_size'],
      dtype='object')

In [3]:
ss.iloc[:5]

,admin_url,buy_decision_time,changes_requested,communication_method_readable,communication_method,created_at,created_by,customer,customer_admin_url,discover_by,...,mainly_puchase_from,monthly_spend,name,parts_type,purchase_frequency_readable,purchase_frequency,recommendation,satisfaction,sending_po_easier,tshirt_size
0,https://www.mrosupply.com/admin/accounts/custo...,1_month,Nothing,Email,3.0,"March 21, 2020, 5:41 p.m.",68402,68402,None,NaN,...,"napa, direct",300,Michael Colligan,V-Belts,Quarterly,5,"price, n/a",10,NaN,Medium
1,https://www.mrosupply.com/admin/accounts/custo...,2_days,Nothing,Phone,1.0,"March 20, 2020, 8:10 p.m.",144092,144091,/admin/accounts/company/144091/change/,NaN,...,"amazon, lowes, localstore",1000,"O&M, Inc","Clamps & Strapping, Cleaning, Fasteners, Hardw...",Monthly,3,"customer service, n/a",10,NaN,2XL
2,https://www.mrosupply.com/admin/accounts/custo...,immediately,Nothing,Phone,1.0,"March 20, 2020, 6:49 p.m.",144059,144059,None,NaN,...,direct,15000,Eric Smith,HVAC,Annually,7,"customer service, n/a",10,True,Extra Large
3,https://www.mrosupply.com/admin/accounts/custo...,1_week,Nothing,Phone,1.0,"March 20, 2020, 5:11 p.m.",76605,76604,/admin/accounts/company/76604/change/,NaN,...,"fastenel, napa, lowes",500,Seger Farms Inc,"Bearings, Motors, Plumbing",Quarterly,5,"customer service, n/a",10,NaN,Large
4,https://www.mrosupply.com/admin/accounts/custo...,immediately,Nothing,Email,3.0,"March 20, 2020, 2:23 p.m.",9704,9703,/admin/accounts/company/9703/change/,NaN,...,"mcmaster, grainger, msc, zoro, fastenel, homed...",1000,Mary Topczewski,Automation,Monthly,3,"other, All of the above!",10,NaN,Extra Large

## How much time usually passes between learning about something you need to purchase and making that purchase?

In [4]:
bdt=ss['buy_decision_time'].value_counts()
bdt_prs=round(ss['buy_decision_time'].value_counts(normalize=True)*100, 1)
s1 = pd.Series(bdt, name='amount')
s2 = pd.Series(bdt_prs, name='percent')
buy_decision_time=pd.concat([s1, s2], axis=1)
buy_decision_time.index.name = 'buy_decision_time'
buy_decision_time.sort_values("percent", ascending=False)

                   amount  percent
buy_decision_time
same_day              171     34.6
a_few_hours           110     22.3
2_days                 75     15.2
immediately            73     14.8
1_week                 28      5.7
3_days                 25      5.1
1_month                12      2.4

## Whatâ€™s the one thing holding you back from buying more on MROSupply?

In [5]:
changes=ss["changes_requested"].values
print(type(changes))
changes[:10]

<class 'numpy.ndarray'>

array(['Nothing', 'Nothing', 'Nothing', 'Nothing', 'Nothing',
       'Nothing, Items Not In Stock', 'Nothing', 'Nothing', 'Nothing',
       'Nothing'], dtype=object)

In [6]:
new_list=[]
for c in changes:
    if "," not in c:
        new_list.append(c)
    else:
        words = c.split(",")
        for w in words:
            new_list.append(w.strip())
new_list[:20]

['Nothing',
 'Nothing',
 'Nothing',
 'Nothing',
 'Nothing',
 'Nothing',
 'Items Not In Stock',
 'Nothing',
 'Nothing',
 'Nothing',
 'Nothing',
 'Nothing',
 'Nothing',
 'Poor Pricing',
 'Nothing',
 'Nothing',
 'Nothing',
 'Nothing',
 'Nothing',
 'Poor Pricing']

In [7]:
def freq_table(array):
    table={}
    total=0
    for i in array:
        total+=1
        key=str(i)
        if key in table:
            table[key]+=1
        else:
            table[key]=1   
    print("total amount is: ",total)
    return table

changes_s=freq_table(new_list)
changes_s

total amount is:  519

{'Nothing': 331,
 'Items Not In Stock': 62,
 'Poor Pricing': 21,
 'Poor Search': 26,
 'Slow Shipping': 41,
 'Warehouses Distance': 20,
 'Unable to Get Credit Terms': 15,
 'Simpler Returns': 3}

In [8]:
total=len(new_list)
changes_series = pd.Series(changes_s)
changes_requested = pd.DataFrame(changes_series, columns=['amount'])
changes_requested["percent"]=round((changes_requested["amount"]/total)*100, 1)
changes_requested.index.name = 'holding_from_buying'
changes_requested.sort_values("percent", ascending=False)

                            amount  percent
holding_from_buying
Nothing                        331     63.8
Items Not In Stock              62     11.9
Slow Shipping                   41      7.9
Poor Search                     26      5.0
Poor Pricing                    21      4.0
Warehouses Distance             20      3.9
Unable to Get Credit Terms      15      2.9
Simpler Returns                  3      0.6

## Which method is most preferable when you have to communicate something to a seller?

In [9]:
com_met=ss['communication_method_readable'].value_counts()
com_met_prs=round(ss['communication_method_readable'].value_counts(normalize=True)*100, 1)
s1 = pd.Series(com_met, name='amount')
s2 = pd.Series(com_met_prs, name='percent')
communication_method=pd.concat([s1, s2], axis=1)
communication_method.index.name = 'pref._communic._method'
communication_method

                        amount  percent
pref._communic._method
Email                      358     72.5
Phone                      108     21.9
Text                        27      5.5
None                         1      0.2

## What is the most important factor when you are making a purchasing decision?

In [10]:
nan=ss['does_price_matter'].isnull()
ss.loc[nan, 'does_price_matter']="Product Availability"
true=ss['does_price_matter']==True
ss.loc[true, 'does_price_matter']="Price"

In [11]:
price=ss['does_price_matter'].value_counts()
price_prs=round(ss['does_price_matter'].value_counts(normalize=True)*100, 1)
s1 = pd.Series(price, name='amount')
s2 = pd.Series(price_prs, name='percent')
price_matter=pd.concat([s1, s2], axis=1)
price_matter.index.name = 'important_factor'
price_matter

                      amount  percent
important_factor
Product Availability     273     55.3
Price                    221     44.7

## Does having a sales rep you know and trust prevent you from leaving that seller?

In [12]:
nan=ss['having_rep'].isnull()
ss.loc[nan, 'having_rep']="No"
true=ss['does_price_matter']==True
ss.loc[true, 'does_price_matter']="Yes"

In [13]:
rep=ss['having_rep'].value_counts()
rep_prs=round(ss['having_rep'].value_counts(normalize=True)*100, 1)
s1 = pd.Series(rep, name='amount')
s2 = pd.Series(rep_prs, name='percent')
have_rep=pd.concat([s1, s2], axis=1)
have_rep.index.name = 'have_rep'
have_rep

          amount  percent
have_rep
No           347     70.2
True         147     29.8

## Which companies do you mainly purchase from today?

In [14]:
purchase=ss["mainly_puchase_from"].values
purchase_list=[]
for c in purchase:
    if "," not in c:
        purchase_list.append(c)
    else:
        words = c.split(",")
        for w in words:
            purchase_list.append(w.strip())

purchase_s=freq_table(purchase_list)

total=len(purchase_list)
purchase_series = pd.Series(purchase_s)
mainly_puchase_from = pd.DataFrame(purchase_series, columns=['amount'])
mainly_puchase_from["percent"]=round((mainly_puchase_from["amount"]/total)*100, 1)
mainly_puchase_from.index.name = 'mainly_puchase_from'
mainly_puchase_from.sort_values("percent", ascending=False)

total amount is:  2032

                        amount  percent
mainly_puchase_from
amazon                     284     14.0
grainger                   248     12.2
homedepot                  179      8.8
mcmaster                   167      8.2
fastenel                   153      7.5
lowes                      147      7.2
zoro                       133      6.5
localstore                 130      6.4
motionindustries           128      6.3
napa                       111      5.5
direct                     109      5.4
msc                         99      4.9
applied                     77      3.8
kaman                       27      1.3
galco                       20      1.0
electricmotorwholesale       8      0.4
walkerindustrial             8      0.4
westerntool                  4      0.2

## What is your typical monthly spend on maintenance, repair and operational parts?
![Image](https://s3.amazonaws.com/mro-supply-sharex/2020/04/hfQHYbiXf0.png)

In [15]:
spends=ss['monthly_spend'].value_counts()
spends_prs=round(ss['monthly_spend'].value_counts(normalize=True)*100, 1)
s1 = pd.Series(spends, name='amount')
s2 = pd.Series(spends_prs, name='percent')
monthly_spend=pd.concat([s1, s2], axis=1)
monthly_spend.index.name = 'monthly_spends'
monthly_spend.sort_values("percent", ascending=False)

                amount  percent
monthly_spends
300                144     29.1
500                 65     13.2
1000                60     12.1
10000               35      7.1
2000                32      6.5
1500                31      6.3
30001               26      5.3
5000                24      4.9
2500                20      4.0
3000                20      4.0
15000               10      2.0
4000                 9      1.8
30000                7      1.4
20000                7      1.4
3500                 4      0.8

## On what type of parts do you usually spend your monthly budget?

In [16]:
parts=ss["parts_type"].values
parts_list=[]
for c in parts:
    if "," not in c:
        parts_list.append(c)
    else:
        words = c.split(",")
        for w in words:
            parts_list.append(w.strip())

parts_s=freq_table(parts_list)

total=len(parts_list)
parts_series = pd.Series(parts_s)
parts_type = pd.DataFrame(parts_series, columns=['amount'])
parts_type["percent"]=round((parts_type["amount"]/total)*100, 1)
parts_type.index.name = 'parts_type TOP 15'
parts_type.sort_values("percent", ascending=False)

total amount is:  2848

                               amount  percent
parts_type TOP 15
Bearings                          199      7.0
Cleaning                          180      6.3
Fasteners                         166      5.8
Electrical                        153      5.4
Tools                             150      5.3
Adhesives                         128      4.5
Sealants and Tape                 128      4.5
Hardware                          114      4.0
V-Belts                            99      3.5
Seals                              99      3.5
Plumbing                           91      3.2
Fleet and Vehicle Maintenance      85      3.0
Hydraulics and Pneumatics          80      2.8
Motors                             80      2.8
Bushings                           76      2.7
Pumps                              71      2.5
Automation                         69      2.4
Safety                             68      2.4
Couplings & Collars                65      2.3
Lighting                           64      2.2
Gears & Gear Rack                  63      2.2
Clamps & Strapping                 57      2.0
Machining                          58      2.0
HVAC                               47      1.7
Lubrication                        47      1.7
Raw Materials                      40      1.4
Sprockets                          41      1.4
Chain                              37      1.3
Sheaves                            38      1.3
Synchronous Belts                  37      1.3
Speed Reducers                     35      1.2
Material Handling                  33      1.2
Conveyors                          32      1.1
Test Instruments                   30      1.1
Clutches and Brakes                26      0.9
Synchronous Pulleys                23      0.8
Rubber                             16      0.6
Furniture and Food Service         13      0.5
Generators                         10      0.4

## What is your frequency of purchase?

In [17]:
frequency=ss['purchase_frequency_readable'].value_counts()
frequency_prs=round(ss['purchase_frequency_readable'].value_counts(normalize=True)*100, 1)
s1 = pd.Series(frequency, name='amount')
s2 = pd.Series(frequency_prs, name='percent')
purchase_frequency=pd.concat([s1, s2], axis=1)
purchase_frequency.index.name = 'purchase_freq'
purchase_frequency

               amount  percent
purchase_freq
Weekly            189     38.3
Monthly           188     38.1
Quarterly          98     19.8
Annually           19      3.8

## If you were recommending MROsupply to a close friend or family member, what exactly would you say?

In [18]:
import re
ss['recommendation']=ss['recommendation'].str.replace(", n/a", "")

def rep(s):
    other = re.search(r"^other", s)
    frs = re.search(r"^free shipping", s)
    price = re.search(r"^price", s)
    inv = re.search(r"^inventory", s)
    csr = re.search(r"^customer service", s)
    if other:
        s="Other"
    elif frs:
        s="Fast & Free Shipping"
    elif price:
        s="Good Price"
    elif inv:
        s="Nice Inventory"
    elif csr:
        s="Excellent Customer Service"
    return s

ss['recommendation']=ss['recommendation'].apply(rep)

recommend=ss['recommendation'].value_counts()
recommend_prs=round(ss['recommendation'].value_counts(normalize=True)*100, 1)
s1 = pd.Series(recommend, name='amount')
s2 = pd.Series(recommend_prs, name='percent')
recommendation=pd.concat([s1, s2], axis=1)
recommendation.index.name = 'recommendation'
recommendation

                            amount  percent
recommendation
Fast & Free Shipping           161     32.6
Good Price                     156     31.6
Nice Inventory                  81     16.4
Excellent Customer Service      76     15.4
Other                           20      4.0

## How would you rate your satisfaction with our company?

In [19]:
satisf=ss['satisfaction'].value_counts()
satisf_prs=round(ss['satisfaction'].value_counts(normalize=True)*100, 1)
s1 = pd.Series(satisf, name='amount')
s2 = pd.Series(satisf_prs, name='percent')
satisfaction_rate=pd.concat([s1, s2], axis=1)
satisfaction_rate.index.name = 'rate_your_satisfaction_with_MRO'
satisfaction_rate
satisfaction_rate=satisfaction_rate.rename(index={10: 'great', 5: 'neutral', 1: 'bad'})
satisfaction_rate

                                 amount  percent
rate_your_satisfaction_with_MRO
great                               445     90.1
neutral                              41      8.3
bad                                   8      1.6

In [20]:
print("Responses who selected satisfaction rate less than 10: ")
ss['likes_least'].value_counts()

Responses who selected satisfaction rate less than 10:

Just placed first order.                                                                                                                              1
They sent me a notice for items they were offering a deal on, and the items weren't even in their possession. Then it was one delay after another.    1
slow on quoting                                                                                                                                       1
Not to bad                                                                                                                                            1
Very slow delivery.                                                                                                                                   1
I was expecting the Hand Sanitizer to in gel form not liquid.                                                                                         1
We ordered on 04-24 then the money was returned and without notice the money was taken againnon 05-04. Better Notification PLEASE                     1
Good. Fast                                                                                                                                            1
only found recently and have order once                                                                                                               1
Last order shipped 9 days later than advertised, very slow response to coms.                                                                          1
I haven't gotten the part yet.                                                                                                                        1
still waiting on my order to arrive                                                                                                                   1
Tried to place order several times. Finally got it to take.                                                                                           1
good overall                                                                                                                                          1
Was told Item shipped but did not.                                                                                                                    1
took longer than expected                                                                                                                             1
long deliveries                                                                                                                                       1
very hard to cancel order                                                                                                                             1
Fine                                                                                                                                                  1
Item shipped later than promised                                                                                                                      1
Not accurate shipping information                                                                                                                     1
always have to order parts                                                                                                                            1
good, with no problems                                                                                                                                1
Have only ordered a few times                                                                                                                         1
Cannot judge-have not received the product yet.                                                                                                       1
Prices are higher, catalog contains too many unavailable products                                                                                     1
Graet price quick turn around sent to wrong address instead of 124th st sent to 12th st                                                               1
We don't often find you are the most efficient way for us to get what we need. When we do, things work pretty well.                                   1
Ordering was fine, cannot provide further until product arrives                                                                                       1
Did not receive my product yet to see the quality but it has been shipped.                                                                            1
Ordered on the 17th and still dont have order but you send me survey tracking number says label printed.                                              1
Shipped 4 days later than promised                                                                                                                    1
Not enough exp to rate. First safety masks from China wasnt reassuring                                                                                1
Have a good deal but it took too long to ship out,.                                                                                                   1
don't like after purchase surveys, won't buy again from MRO                                                                                           1
change their mine about the lead time to much looks like the inventory is not to accurate                                                             1
Slow order processing. Order placed on 7-21 did not ship until 7-23.                                                                                  1
No complaints                                                                                                                                         1
Its been ok.                                                                                                                                          1
Ordering hand sanitizer, and items were out of stock and substituted. It's also taking a couple weeks to service the order.                           1
Neutral , I need to get more familiar with you in order to rate.                                                                                      1
bad sales service                                                                                                                                     1
I ordered hand sanitizer and have waited longer than indicated when I placed the order                                                                1
Experience would be better with a net 30 account. If I'm forced to use credit card, then I have time to ship around                                   1
had to inquire the status of order before receiving information                                                                                       1
It has been good. In these times it is difficult to grade.                                                                                            1
Extremely long time to ship                                                                                                                           1
ok                                                                                                                                                    1
Fine just been the first purchase so far                                                                                                              1
Long lead times                                                                                                                                       1
They generally have what we need. Not the quality of service from reps that we used to get from them.                                                 1
Name: likes_least, dtype: int64

## Would you prefer to send POs directly to someone or some place?

In [21]:
nan=ss['sending_po_easier'].isnull()
ss.loc[nan, 'sending_po_easier']="No"
true=ss['sending_po_easier']==True
ss.loc[true, 'sending_po_easier']="Yes"

In [22]:
sendPO=ss['sending_po_easier'].value_counts()
sendPO_prs=round(ss['sending_po_easier'].value_counts(normalize=True)*100, 1)
s1 = pd.Series(sendPO, name='amount')
s2 = pd.Series(sendPO_prs, name='percent')
prefer_send_PO=pd.concat([s1, s2], axis=1)
prefer_send_PO.index.name = 'send PO'
prefer_send_PO

         amount  percent
send PO
No          328     66.4
Yes         166     33.6

## What size T shirt would you like?

In [23]:
shirt=ss['tshirt_size'].value_counts()
shirt_prs=round(ss['tshirt_size'].value_counts(normalize=True)*100, 1)
s1 = pd.Series(shirt, name='amount')
s2 = pd.Series(shirt_prs, name='percent')
Tshirt_size=pd.concat([s1, s2], axis=1)
Tshirt_size

             amount  percent
Extra Large     149     34.5
Large           109     25.2
2XL             108     25.0
Medium           56     13.0
Small            10      2.3